/** HTML entity decoding shared by the DOM parser and lightweight scrapers; dependency-free. */

const NAMED_ENTITIES: Record<string, string> = {
	AElig: "Æ",
	Aacute: "Á",
	Acirc: "Â",
	Agrave: "À",
	Aring: "Å",
	Atilde: "Ã",
	Auml: "Ä",
	Ccedil: "Ç",
	ETH: "Ð",
	Eacute: "É",
	Ecirc: "Ê",
	Egrave: "È",
	Euml: "Ë",
	Iacute: "Í",
	Icirc: "Î",
	Igrave: "Ì",
	Iuml: "Ï",
	Ntilde: "Ñ",
	Oacute: "Ó",
	Ocirc: "Ô",
	Ograve: "Ò",
	Oslash: "Ø",
	Otilde: "Õ",
	Ouml: "Ö",
	THORN: "Þ",
	Uacute: "Ú",
	Ucirc: "Û",
	Ugrave: "Ù",
	Uuml: "Ü",
	Yacute: "Ý",
	aacute: "á",
	acirc: "â",
	aelig: "æ",
	agrave: "à",
	aring: "å",
	atilde: "ã",
	auml: "ä",
	amp: "&",
	apos: "'",
	bull: "•",
	brvbar: "¦",
	ccedil: "ç",
	cedil: "¸",
	cent: "¢",
	copy: "©",
	deg: "°",
	curren: "¤",
	divide: "÷",
	emsp: " ",
	ensp: " ",
	euro: "€",
	eacute: "é",
	ecirc: "ê",
	egrave: "è",
	eth: "ð",
	euml: "ë",
	frac12: "½",
	frac14: "¼",
	frac34: "¾",
	gt: ">",
	iacute: "í",
	icirc: "î",
	iexcl: "¡",
	igrave: "ì",
	iquest: "¿",
	iuml: "ï",
	hellip: "…",
	laquo: "«",
	ldquo: "“",
	lsquo: "‘",
	lt: "<",
	mdash: "—",
	macr: "¯",
	micro: "µ",
	middot: "·",
	nbsp: " ",
	ndash: "–",
	ntilde: "ñ",
	oacute: "ó",
	ocirc: "ô",
	ograve: "ò",
	ordf: "ª",
	ordm: "º",
	oslash: "ø",
	otilde: "õ",
	ouml: "ö",
	para: "¶",
	pound: "£",
	plusmn: "±",
	quot: '"',
	raquo: "»",
	rdquo: "”",
	reg: "®",
	rsquo: "’",
	sect: "§",
	shy: "­",
	szlig: "ß",
	thorn: "þ",
	sup1: "¹",
	sup2: "²",
	sup3: "³",
	thinsp: " ",
	times: "×",
	trade: "™",
	uacute: "ú",
	ucirc: "û",
	ugrave: "ù",
	uml: "¨",
	uuml: "ü",
	yacute: "ý",
	yuml: "ÿ",
	yen: "¥",
};

const ENTITY_PATTERN = /&(#(?:x[0-9a-f]+|\d+)|[a-z][a-z0-9]+);/gi;

/** Decode common named entities and all valid numeric character references. */
export function decodeEntities(value: string): string {
	if (!value.includes("&")) return value;
	return value.replace(ENTITY_PATTERN, (whole, entity: string) => {
		if (entity[0] !== "#") return NAMED_ENTITIES[entity] ?? NAMED_ENTITIES[entity.toLowerCase()] ?? whole;
		const hexadecimal = entity[1]?.toLowerCase() === "x";
		const codePoint = Number.parseInt(entity.slice(hexadecimal ? 2 : 1), hexadecimal ? 16 : 10);
		if (
			!Number.isFinite(codePoint) ||
			codePoint <= 0 ||
			codePoint > 0x10ffff ||
			(codePoint >= 0xd800 && codePoint <= 0xdfff)
		) {
			return "�";
		}
		return String.fromCodePoint(codePoint);
	});
}
